import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Gallery · Docs',
  description: 'How the WokGen community gallery works — viewing, sharing, and exploring assets.',
};

export default function DocsGallery() {
  return (
    <div className="docs-page">
      <div className="docs-page-inner">

        {/* Sidebar */}
        <aside className="docs-sidebar">
          <Link href="/docs" className="docs-back">← Docs Hub</Link>
          <div className="docs-sidebar-mode">
            <span>🖼</span> Gallery
          </div>
          <nav className="docs-toc">
            <a href="#overview" className="docs-toc-link">Overview</a>
            <a href="#browsing" className="docs-toc-link">Browsing</a>
            <a href="#sharing" className="docs-toc-link">Sharing</a>
            <a href="#modes" className="docs-toc-link">Mode Galleries</a>
            <a href="#download" className="docs-toc-link">Downloading</a>
          </nav>
          <div className="docs-sidebar-links">
            <Link href="/pixel/gallery" className="docs-toc-link">Pixel Gallery →</Link>
            <Link href="/business/gallery" className="docs-toc-link">Business Gallery →</Link>
          </div>
        </aside>

        {/* Content */}
        <main className="docs-content">
          <div className="docs-content-header">
            <h1 className="docs-title">Gallery</h1>
            <p className="docs-subtitle">Browse community-generated assets, share your own creations, and find inspiration across all WokGen modes.</p>
          </div>

          <section id="overview">
            <h2 className="docs-h2">Overview</h2>
            <p className="docs-p">Each product mode in WokGen has its own gallery — a curated feed of publicly shared assets generated by the community. Galleries are mode-specific: Pixel Gallery shows only pixel art game assets, Business Gallery shows only brand and marketing assets, and so on.</p>
            <p className="docs-p">You do not need to be signed in to browse galleries. Sign in to share your own generations or filter to see only your assets.</p>
          </section>

          <section id="browsing">
            <h2 className="docs-h2">Browsing</h2>
            <p className="docs-p">Gallery pages support infinite scroll — new assets load automatically as you scroll down. You can filter by:</p>
            <ul className="docs-ul">
              <li className="docs-li"><strong>Community / Mine</strong> — Toggle between all public assets and your own generations</li>
              <li className="docs-li"><strong>Tool filter</strong> — Filter by generation tool (e.g., Logo, Brand Kit, Sprite, Tileset)</li>
              <li className="docs-li"><strong>Search</strong> — Filter by prompt text to find specific asset types</li>
            </ul>
            <p className="docs-p">Click any asset card to open the lightbox view with a larger preview, the prompt used, and action buttons.</p>
          </section>

          <section id="sharing">
            <h2 className="docs-h2">Sharing to Gallery</h2>
            <p className="docs-p">To share a generation to the public gallery, toggle the <code className="docs-code">Share to Gallery</code> switch in the Studio before generating. This will make your generated asset publicly visible in the community gallery with its prompt.</p>
            <div className="docs-callout docs-callout--warn">
              <span className="docs-callout-icon">⚠</span>
              <span>Prompts are visible when assets are shared. Do not include personal information, brand names you don&apos;t own, or confidential details in prompts you intend to share.</span>
            </div>
            <p className="docs-p">You can turn off sharing at any time — past public assets remain public unless deleted from your account history.</p>
          </section>

          <section id="modes">
            <h2 className="docs-h2">Mode Galleries</h2>
            <div className="docs-table-wrap">
              <table className="docs-table">
                <thead>
                  <tr><th>Mode</th><th>Gallery URL</th><th>Asset Types</th></tr>
                </thead>
                <tbody>
                  <tr><td>Pixel</td><td><code className="docs-code">/pixel/gallery</code></td><td>Sprites, tilesets, characters, UI elements</td></tr>
                  <tr><td>Business</td><td><code className="docs-code">/business/gallery</code></td><td>Logos, brand kits, slides, social banners</td></tr>
                  <tr><td>Vector</td><td>Coming soon</td><td>SVG icons, illustrations</td></tr>
                  <tr><td>Emoji</td><td>Coming soon</td><td>Emoji packs, stickers, app icons</td></tr>
                  <tr><td>UI/UX</td><td>Coming soon</td><td>Components, layouts, pages</td></tr>
                </tbody>
              </table>
            </div>
            <p className="docs-p">Galleries will never mix assets from different modes. Each mode&apos;s gallery maintains strict visual and contextual separation.</p>
          </section>

          <section id="download">
            <h2 className="docs-h2">Downloading Assets</h2>
            <p className="docs-p">You can download any asset from the gallery lightbox using the Download button. Files are served as PNG images (or GIF for animations).</p>
            <p className="docs-p">All assets generated on WokGen can be used in your projects. Standard generations (Pollinations) are free for personal and commercial use. HD generations may have additional model-specific licensing from the underlying provider.</p>
          </section>

          <div className="docs-content-footer">
            <Link href="/pixel/gallery" className="btn-primary btn-sm">Pixel Gallery →</Link>
            <Link href="/business/gallery" className="btn-ghost btn-sm">Business Gallery →</Link>
          </div>
        </main>
      </div>
    </div>
  );
}
